.github/workflows/crates.yml

Only publish crates on a tag being pushed.
Fixes #9.

gh-workflow/crates: only publish crates on tags

---

rust/Cargo.lock
rust/its-client/Cargo.toml
rust/its-client/src/main.rs
rust/libits-client/Cargo.toml
rust/libits-client/src/analyse/configuration.rs
rust/libits-client/src/pipeline.rs
rust/libits-copycat/Cargo.toml

New features
* Add a raw key/value HashMap to store custom settings that are application related
Configuration struct is already provided to the analyser, adding custom settings directly through that struct ease the use of external user/application related configuration through the pipeline

Add editable settings to Configuration

---

python/Dockerfile
python/its_client/__init__.py
python/setup.py

Let's generate the wheel:
```
/home/kvmk8371/workspace/its-client/python/venv/bin/python /home/kvmk8371/workspace/its-client/python/setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running egg_info
writing its_client.egg-info/PKG-INFO
writing dependency_links to its_client.egg-info/dependency_links.txt
writing entry points to its_client.egg-info/entry_points.txt
writing requirements to its_client.egg-info/requires.txt
writing top-level names to its_client.egg-info/top_level.txt
reading manifest file 'its_client.egg-info/SOURCES.txt'
writing manifest file 'its_client.egg-info/SOURCES.txt'
/home/kvmk8371/workspace/its-client/python/venv/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is …
```

Remove pytest to wheel

---

rust/Cargo.lock

Nothing to test : the lock was just not updated

rust: propagate the forget version update to 1.1.1

---

python/its_client/logger/logger.py
python/its_client/logger/monitoring.py
python/its_client/mqtt/mqtt_client.py
python/its_client/roi.py

New features
* ROI based CPM subscription
* CPM message reception monitoring
How to test
1. Start the client and filter its output on CPM
```
PYTHONPATH=.. ./main.py --mqtt-host <broker_ip> --mqtt-port <mqtt_port> --mqtt-username <username> --mqtt-password <password> --mqtt-client-id <unique_id> --log-level INFO --geo-position=static | grep cpm
```
**=> You must see logs about CPM queue subscription**
> 2022-04-15 17:18:51,232 INFO: we subscribed on topic 5GCroCo/outQueue/v2x/cpm/+/1/2/0/2/2/2/0/2/3/1/0/3/1/1/2/0/0/0/#
2. Send fake CPM
_You can use [this script](https://gist.github.com/nbuffon/ccb2479b6fd300811d05b0b2d1c6e35c) to generate a CPM that is inside the client's ROI_
**=> You must see logs about CPM reception**
> 2022-04-15 17:22:56,240 INFO: …

Cpm management

---

python/Dockerfile
python/setup.py
rust/Cargo.lock
rust/its-client/Cargo.toml
rust/libits-client/Cargo.toml
rust/libits-copycat/Cargo.toml

Increase components versions
=======================
rust: bump all components to 1.2.0
----------------------------------------------    
- libits-client: 1.2.0
* GeoExtension now implements Ord trait
* Replaced deprecated usage of geo_types::{lon, lat} methods by geo_types::{x, y}
* Rust edition bumped to 2021
- its-client: 1.2.0
* Rust edition bumped to 2021
- libits-copycat: 1.2.0
* Rust edition bumped to 2021
python: bump package version to 1.2.1
---------------------------------------------------
* CPM messages are now subscribed to and logged
* Region of interest has been extended to nine tiles
The one we're in plus the eight surrounding
* Minor typo fixes

Bump packages versions

---

schema/cam_schema_1-1-1.json
schema/cam_schema_1-1-2.json
schema/validate

The CAM schema was not validating against the 2020-12 Draft schema, because of a misplaced `$comment` key.
Fix that, and introduce a small helper script to validate schemas.
Since the schema changed, also bump its version.

schema/cam: fix schema validity

---

.github/workflows/python.yml
python/its_client/main.py
python/its_client/position/static.py
python/its_client/test/its_client.cfg
python/its_client/test/test_configuration.py

New features
* **python**: add configuration items to fake altitude, heading, and speed
How to test
1. Create a test config file, replace the MQTT settings to match your setup:
```
[broker]
host=test_host
port=18
tls_port=88
username=test_user
password=test_password
client_id=test_client_id
[position]
static=true
latitude=44.50779
longitude=2.209381
heading=130.7275
speed=0.103
altitude=131.693
[log]
directory=.
default_level=DEBUG
```
2. Start the its-client with that config file:
```
$ its-client -c /path/to/config/
```
3. Check the values emitted in the MQTT broker shall match the values from the config file:
```
$ mosquitto_sub -h test_host -p 18 -v -t '#'
```
**Notes:** the black change can be seen in [this …

python/its-client: add more static position items

---

.github/workflows/python_its-status.yml
python/its-status/its-status.cfg
python/its-status/its_status/__init__.py
python/its-status/its_status/collector.cellular.py
python/its-status/its_status/collector.static.py
python/its-status/its_status/collector.system.py
python/its-status/its_status/collector.time_sources.py
python/its-status/its_status/emitter.mqtt.py
python/its-status/its_status/emitter.stdout.py
python/its-status/its_status/helpers.py
python/its-status/its_status/main.py
python/its-status/setup.cfg
python/its-status/setup.py

**New features:**
* `its-status`: new python client to publish ITS status messages that match the status schema
---
1. build and install `python/its-status` with standard setuptools procedure;
2. create a configuration file, using `its-status.cfg` as startup point, adapt with your MQTT broker and credentials, enable the `stdout` emitter;
3. subscribe an MQTT client to your broker, on the status topic, e.g. with mosquitto CLI clients:
```sh
$ mosquitto_sub -h BROKER -p PORT -u USERNAME -P PASSWORD -i ID -t 'status/#'
```
4. run `its-status` using your custom configuration file:
```sh
$ its-status -c /path/to/its-status.custom.cfg
```
---
1. The `its-status` package is installed;
2. You have a custom configuration file with your MQTT settings;
3. The …

python/its-status: new client, to publish ITS status messages

---

.github/workflows/python_its-client.yml
python/its-client/its_client/configuration.py
python/its-client/its_client/its_client.cfg
python/its-client/its_client/main.py
python/its-client/its_client/mqtt/mqtt_client.py
python/its-client/its_client/test/its_client.cfg
python/its-client/its_client/test/test_configuration.py

**New features:**
* `its-client`: mirror MQTT traffic to another broker
---
1. build and install `python/its-clients` with standard setuptools procedure;
2. Start a local broker and listen on it:
```
$ mosquitto -c /dev/null -p 11883 -d
$ mosquitto_sub -p 11883 -t '5GCroCo/#'
```
3. Uncomment and update the `mirror-boker` section in `its_client.cfg`:
```
[mirror-broker]
host = localhost
port = 11883
mirror-self = false
```
4. Start `its-client` with that config file (warning, the path to the config file is in fact the path to the directory containing the config file):
```
$ its-client -c /path/to/its_client/
```
Note: do not forget to kill the MQTT broker that is in the background...
---
1. The `its-client` package is installed
2. The MQTT broker …

python/its-client: mirror MQTT traffic to another broker

---

python/its-client/its_client/configuration.py
python/its-client/its_client/its_client.cfg
python/its-client/its_client/logger/logger.py
python/its-client/its_client/main.py
python/its-client/its_client/mqtt/mqtt_client.py
python/its-client/its_client/mqtt/mqtt_worker.py
python/its-client/its_client/roi.py
python/its-client/its_client/test/its_client.cfg

**New features:**
* `its-client`: make the MQTT topics configurable
* `its-client`: make the logfiles rotation configurable
---
1. build and install `python/its-clients` with standard setuptools procedure;
2. Start a local broker and listen on it:
```
$ mosquitto -c /dev/null -p 11883 -d
$ mosquitto_sub -p 11883 -t '5GCroCo/#'
```
3. Prepare a configuration file (or used the default one) with log settings and
and MQTT topic settings, then start `its-client` with the configuration file:
```
$ its-client -c /path/to/its_client/
```
4. Check the log file rotation
5. Check the MQTT topics
Note: do not forget to kill the MQTT broker that is in the background...
---
1. The `its-client` package is installed
2. The MQTT broker starts, the MQTT listener, …

python/its-client: new options for configurable MQTT topics and for log files size and number

---

python/its-status/its-status.cfg
python/its-status/its_status/collector.gnss.py
python/its-status/its_status/collector.static.py
python/its-status/its_status/collector.system.py
python/its-status/its_status/collector.time_sources.py
schema/status_schema_1-1-0.json

**New features:**
* schemas: extend status schema with new data
* add GNSS status
* extend time sources
* adjust top-level `type`, add hardware type
* tag version 1.1.0
* `its-status`: extend for status schema 1.1.0 (above)
---
1. build and install `python/its-status` with standard setuptools procedure;
2. create a configuration file, using `its-status.cfg` as startup point, adapt with your MQTT broker and credentials, enable the `stdout` emitter;
3. subscribe an MQTT client to your broker, on the status topic, e.g. with mosquitto CLI clients:
```sh
$ mosquitto_sub -h BROKER -p PORT -u USERNAME -P PASSWORD -i ID -t 'status/#'
```
4. run `its-status` using your custom configuration file:
```sh
$ its-status -c /path/to/its-status.custom.cfg
```
---
1. …

schemas/status: extend with new fields

---

schema/cam_schema_1-1-3.json
schema/cpm_schema_1-2-1.json
schema/denm_schema_1-1-3.json

To help our international, non-french users, use english notation for floating point, rather than the french one, in the description of the fields in the schemas.
Fixes: #42

schema: use dots in floating-point notation

---

python/its-status/its_status/collector.gnss.py
python/its-status/its_status/collector.static.py

**Bug fix:**
* GNSS reports software identification as `version` instead of `software` as defined in schema 1.1.0.
* status messages still advertise being version 1.0.0, even though they are version 1.1.0
---
See #43.
---
See #43.

python/status: fix status messages to comply with schema 1.1.0

---

python/its-client/its_client/mqtt/mqtt_client.py

**Bug fix:**
* #57
---
Pre-requisites: an MQTT broker running
1. Check the messages on your MQTT broker, displaying topic (`%t`) and payload (`%p`):
```sh
$ mosquitto_sub -t '#' -F '%t %p'
```
2. Configure its-client to connect to your MQTT broker as a mirror broker, without mirroring self; run its-client
3. Configure its-client to connect to your MQTT broker as a mirror broker, with mirroring self; run its-client
---
1. The messages are displayed as they are emitted
2. The messages are all on the outQueue
3. The messages are all on the outQueue, and the CAM is duplicated from the one on the inQueue.

python/its-client: send own messages to the outQueue of the local broker

---

.github/workflows/python_its-info.yml
python/its-info/its-info.cfg
python/its-info/its_info/main.py
python/its-info/setup.py
schema/information_schema_1-2-0.json

**Features:**
* _its-info_: a new client to send ETSI information messages
---
Preparatory steps: have a MQTT broker running.
1. Build and install the package in `python/its-info/` with the standard
setup-tools procedure:
```sh
$ cd python/its-info/
$ pip3 wheel .
$ pip3 install its_info-0.0.0-py3-none-any.whl
```
Note where the `its-info` is installed, e.g. `${HOME}/.local/bin`
2. Update the configuration `its-info.cfg` to match your local setup,
especially the MQTT broker settings; choose a short period, like a
few seconds.
3. Run a MQTT client that listens on the `info` topic (or whatever you
configured in `its-info.cfg`):
```sh
$ mosquitto_sub -h BROKER -p PORT -u USERNAME -P PASSWORD -i ID -t info
```
4. Run the client, and wait for a few periods (as configured in …

python/its-info: new client to send info messages

---

python/its-status/its_status/collector.cellular.py
python/its-status/its_status/collector.system.py

**Bug fix:**
* `its-status`: fix API of {cellular,system} collectors
Fixes: 295544cefde1841b7947e7f8aa53cdcb6847df5f and #54
---
1. build and install `python/its-status` with standard setuptools procedure, e.g.:
```sh
$ pip3 wheel .
$ pip3 install its_status-0.0.0-py3-none-any.whl
```
Also take not of where the script has been installed (e.g. `${HOME}/.local/bin`)
2. create a configuration file, using `its-status.cfg` as startup point, adapt with your
MQTT broker and credentials, enable the `stdout` emitter;
3. subscribe an MQTT client to your broker, on the status topic, e.g. with mosquitto CLI clients:
```sh
$ mosquitto_sub -h BROKER -p PORT -u USERNAME -P PASSWORD -i ID -t 'status/#'
```
4. run `its-status` using your custom configuration file:
```sh
$ …
```

python/its-status: fix API of {cellular,system} collectors

---

python/its-status/its-status.cfg
python/its-status/its_status/collector.system.py

**New feature:**
* `its-status`:
* add config option for the data directory (#63)
* be resilient against older lshw versions
---
1. build and install `python/its-status` with standard setuptools procedure, e.g.:
```sh
$ pip3 wheel .
$ pip3 install its_status-0.0.0-py3-none-any.whl
```
Also take note of where the script has been installed (e.g. `${HOME}/.local/bin`)
2. create a configuration file, using `its-status.cfg` as startup point, adapt with your
MQTT broker and credentials, change the data directory to a writable location, and
enable the `stdout` emitter;
3. subscribe an MQTT client to your broker, on the status topic, e.g. with mosquitto_sub
CLI client:
```sh
$ mosquitto_sub -h BROKER -p PORT -u USERNAME -P PASSWORD -i ID -t 'status/#'
```
5. run `its-status` …

python/its-status: add config option for the data directory

---

python/its-client/its_client/cam.py
python/its-client/its_client/mobility.py
python/its-client/its_client/mqtt/mqtt_client.py
python/its-client/its_client/mqtt/mqtt_worker.py

Bug fix:
* #75 
* #76 
Fixes: #76 #75
---
1. Build and install `python/its-client` with standard setuptools procedure, e.g. (replace XXXXX by appropriate values):
```sh
$ cd python/its-client
$ pip3 wheel .
$ pip3 install its_client-XXXXX.whl
```
Also take note of where the script has been installed (e.g. `${HOME}/.local/bin`)
2. Run its-client in a setup where there is an actual GNSS device driven by gpsd
3. Move around a large area (preferably with a car in an area of at least 200m × 200m)
---
1. The `its-client` package is installed;
2. The `its-client` program runs, receives data from gpsd, and emits CAM messages
3. The CAM messages contain correct acceleration values; the `its-client` program
terminates immediately when there is an MQTT issue …

python/its-client: fix acceleration

---

python/its-status/its_status/collector.cellular.py
python/its-status/its_status/collector.static.py
schema/status_schema_1-2-0.json

**New feature:**
* `its-status`: collect and report signal KPIs for all radios
Closes: #74
---
Prerequisites: a machine with a cellular modem, preferably one that is capable
of using more than one radio per connection.
1. build and install `python/its-status` with standard setuptools procedure, e.g.:
```sh
$ pip3 wheel .
$ pip3 install its_status-0.0.0-py3-none-any.whl
```
Also take note of where the script has been installed (e.g. `${HOME}/.local/bin`)
2. create a configuration file, using `its-status.cfg` as startup point, adapt with your
MQTT broker and credentials (or disable MQTT altogether), and enable the `stdout` emitter;
3. run `its-status` using your custom configuration file:
```sh
$ ${HOME}/.local/bin/its-status -c /path/to/its-status.custom.cfg
```
--- …

python/its-status: collect all cellular KPIs

---

THIRD-PARTY.md
rust/Cargo.lock
rust/libits-client/Cargo.toml
rust/libits-client/src/reception/exchange/collective_perception_message.rs
rust/libits-client/src/reception/exchange/map_extended_message.rs
rust/libits-client/src/reception/exchange/mobile_perceived_object.rs
rust/libits-client/src/reception/exchange/reference_position.rs

What's new
----------------
* Add missing `free_space_addendum_container` in `CollectivePerceptionMessage`
* Add missing `stationary_sensor_*` fields in `DetectionArea`
* Add corresponding structs definitions for
* StationarySensorRadial
* CircularArea
* EllipticArea
* RectangleArea
* Offset
* Add `is_pedestrian_lane` in `MAPExtendedMessage`

Cpm missing structs

---

.github/workflows/rust.yml
rust/Cargo.lock
rust/libits-client/Cargo.toml

New features
-------------------
* rust: bump `geo` dependency to version `0.26`
* workflow: add Rust release build in checks
How to test
1. Build in release mode
```
cargo clean
cargo build --release
```
2. Run the CopyCat example in release mode
```
cargo run --release --bin its-client -- -H <broker_host> -P <broker_port> -u <username> -p <password> --mqtt-client-id <client_id>
```
**=> stdout logs tells that the copycat receives messages (cam, denm, ...)**  
3. Check the applicative logs
```
tail -F log/its-client_rCURRENT.log
```
**=> Logs must tell about either copy/retain moving vehicle messages or stopped vehicle that are not copied**

rust: update geo crate to 0.26

---

python/its-client/its_client/configuration.py

Bug fix:
* MQTT port for mirror broker from config file unused
---
1. Build and install `python/its-client` with standard setuptools procedure, e.g. (replace XXXXX by appropriate values):
```sh
$ cd python/its-client
$ pip3 wheel .
$ pip3 install its_client-XXXXX.whl
```
Also take note of where the script has been installed (e.g. `${HOME}/.local/bin`)
2. In the config file, enable the mirroring to a broker running on a non-standard port.
3. Run `its-client` using your custom config file.
---
1. The `its-client` package is installed;
2. The config file contains an entry with, most notably (port depends on your setup):
```ini
[mirror-broker]
port = 1234
```
3. The `its-client` runs and sends messages to the mirror broker.

python/its-client: expect explicit port for mirror broker

---

rust/libits-client/src/mqtt/topic/geo_extension.rs

What's new
* rust: GeoExtension struct no longer impl Ord
Both Ord and PartialOrd were defining different behaviours
While this was initially done intentionally the Ord implementation is no longer required and has been remove as it reduce the risk of confusion
Related to #101 
How to test
1. Run the copycat example 
```
cargo run --bin its-client -- -H 90.84.199.250 -P 11883 -u <username> -p <password> --mqtt-client-id ora_copycat
```
**=> You must received and send CAM messages**

rust: remove Ord impl for GeoExtension

---

python/its-interqueuemanager/its-iqm.cfg
python/its-interqueuemanager/its_iqm/authority/__init__.py
python/its-interqueuemanager/its_iqm/authority/file.py
python/its-interqueuemanager/its_iqm/authority/http.py
python/its-interqueuemanager/its_iqm/authority/mqtt.py
python/its-interqueuemanager/its_iqm/iqm.py
python/its-interqueuemanager/its_iqm/main.py
python/its-interqueuemanager/its_iqm/mqtt_client.py
python/its-interqueuemanager/neighbours.cfg
python/its-interqueuemanager/neighbours.json
python/its-interqueuemanager/setup.py

**Changes:**
- closes #103 
- closes #107
- preemptive fixups in MQTT authority client
- code reorganisation
- coding style cleanups
---
Note: you'll need an MQTT broker that allows anonymous connections, listening on port 1883 on local host. To display the traffic on the broker, start a mosquitto client (`%t` displays the topic, `%p` the payload): `mosquitto_sub -t '#' -F '%t %p'`
1. Build and install its-iqm:
```sh
$ pip3 install .
```
Note the installation path (e.g. /home/login/.local/bin).
2. Prepare configuration files:
1. the `iqm.cfg` configuration file:
```ini
[general]
instance-id = iqm-1
prefix = 5G-root
suffix = v2x
[local]
host = 127.0.0.1
port = 1883
[authority]
type = file
reload = 5
path = neighbours.cfg
[neighbours]
client_id = neighbour-1
```
2. the …

python/iqm: fix #103, #107; misc fixes and cleanups

---

rust/src/exchange/etsi.rs
rust/src/exchange/etsi/decentralized_environmental_notification_message.rs

What's new
* Fixed `etsi_now()` function
It was using timestamp_**from**_etsi() instead of timestamp_**to**_etsi() 
* Fixed DecentralizedEmergencyNotificationMessage `timeout()` and `remaining_time()` 
* Dedicated unit tests added for both previous points

Fix etsi timestamp

---

python/its-quadkeys/its_quadkeys/quadkeys.py
python/its-quadkeys/quadkeys-test

**Changes:**
* closes #130 
---
1. Run the non-regression test-suite:
```sh
$ cd python/its-quadkeys
$ ./quadkeys-test
```
---
1. The regerssion test-suite terminates without any error:
```
QuadKey empty: OK
QuadKey in: OK
QuadKey not in: OK
QuadKey split (depth): OK
QuadKey split (extra_depth): OK
QuadKey shallower: OK
QuadKey root: OK
QuadKey neighbours: OK
QuadKey from lat/lon/depth: OK
QuadZone optimise: OK
QuadZone optimise (merge-reduce): OK
QuadZone serialise: OK
QuadZone neighbours (depth 7): OK
QuadZone neighbours (depth 6): OK
QuadZone addition (neighbours 7): OK
QuadZone addition (neighbours 6): OK
QuadZone intersection: OK
QuadZone substraction (neighbours 7): OK
QuadZone substraction (neighbours 6): OK
QuadZone substraction (quadkeys): …
```

python: fix issue #130

---

python/its-quadkeys/its_quadkeys/quadkeys.py
python/its-quadkeys/quadkeys-test

**Bug fix:**
Fixes: #147 
---
1. Install the requirements (you may do so in a _venv_):
```sh
$ cd python/its-quadkeys
$ pip3 install -r requirements.txt
```
2. Run the regression test suite (in the same _venv_ as step 1 if you used one):
```sh
$ ./quadkeys-test
```
---
1. The requirements are installed.
2. There is no failure in the test suite.

python/its-quadkeys: fix neighbouring for nothern and southern borders

---

python/iot3/LICENSE
python/iot3/README.md
python/iot3/pyproject.toml
python/iot3/src/iot3/core/__init__.py
python/iot3/src/iot3/core/mqtt.py
python/iot3/src/iot3/core/otel.py
python/iot3/tests/test-iot3-core
python/iot3/tests/test-iot3-core-all
python/iot3/tests/test-iot3-core-mqtt
python/iot3/tests/test-iot3-core-otel

---
**Features**;
* Implement IoT3 Core SDK:
* MQTT client
* OpenTelemetry client
* telemetry sent for MQTT messages
Closes: #123
Closes: #122
---
1. Prepare an OpenTelemetry collector on localhost:
```
--rm \
-p 4318:4318 \
```
then open a browser on the Jaegger UI:
```
http://localhost:16686/
```
2. Prepare an MQTT broker on localhost (adapt based on your distribution):
```sh
$ sudo systemctl start mosquitto.service
```
and then start an MQTT client to dump the messages on the broker:
```
$ mosquitto_sub -V 5 -t '#' -F '%j' |jq .
```
3. Test IoT3 Core SDK:
1. start an environment with python 3.11:
```sh
--rm \
-ti \
-e …
```

python: implement IoT3 Core SDK

---

python/its-interqueuemanager/its_iqm/iqm.py

**Bug fix:**
* closes #170
---
1. start two MQTT brokers; 1234 is considered "local", and 1235 is considered the "neighbour"; start an MQTT client on the local broker:
```sh
$ mosquitto -p 1234
$ mosquitto -p 1235
$ mosquitto_sub -p 1234 -t '#' -F '%U %t %p'
```
2. Install IoT3 Core SDK and its-iqm:
1. start a docker container with python 3.11 (if you already have python 3.11 or later on your machine, you don't need the container):
```sh
--rm \
-ti \
-e no_proxy \
--entrypoint /bin/bash \
python:3.11.9-slim-bookworm
```
2. create and activate a venv to install into:
```sh
(docker)$ python3 -m venv …
```

python/iqm: fix subscribing to neighbours

---

python/iot3/src/iot3/core/mqtt.py
python/iot3/tests/test-iot3-core
python/iot3/tests/test-iot3-core-all
python/iot3/tests/test-iot3-core-mqtt
python/iot3/tests/test-iot3-core-otel
python/its-info/its-info.cfg
python/its-info/its_info/main.py
python/its-interqueuemanager/its-iqm.cfg
python/its-interqueuemanager/its_iqm/authority/http.py
python/its-interqueuemanager/its_iqm/authority/mqtt.py
python/its-interqueuemanager/its_iqm/iqm.py
python/its-interqueuemanager/its_iqm/main.py
python/its-status/its-status.cfg
python/its-status/its_status/emitter.mqtt.py
python/its-vehicle/its-vehicle.cfg
python/its-vehicle/its_vehicle/main.py
python/its-vehicle/its_vehicle/roi.py

---
**Features**;
* IoT3 Core SDK:
* Implement MQTT over TLS
* Implement MQTT over websockets
Closes: #138
---
1. start an environment with python 3.11 in the IoT3 Core SDK directory:
```sh
$ cd python/iot3/
--rm \
-ti \
-e no_proxy \
--entrypoint /bin/bash \
python:3.11.9-slim-bookworm
```
2. create a /venv/ in a writable location, and activate it:
```sh
(docker) python3 -m venv /tmp/iot3
(docker) . /tmp/iot3/bin/activate
```
3. install the IoT3 Core SDK (notice the trailing dot `.`):
```sh
(docker) pip3 --disable-pip-version-check install .
```
4. Start an MQTT client:
```sh
mosquitto_sub \
-h …
```

python/iot3: implement TLS and Websockets

---

rust/Cargo.lock
rust/Cargo.toml
rust/examples/config.ini
rust/src/client/configuration.rs
rust/src/client/configuration/telemetry_configuration.rs
rust/src/transport/mqtt.rs
rust/src/transport/telemetry.rs

What's new
- Manage basic auth for telemetry
- No longer require a certificate for MQTTS, the server certificate has to be signed by a trusted authority ( closes #140 )
How to test
1. Setup the `[telemetry]` section in config.ini to point to an OTLP collector requiring basic auth
2. Start the telemetry example
```
cargo run --example telemetry --features telemetry
```
**=> Logs yields about traces being sent and no connection error is raised**
3. Check on jaeger that you correctly see the traces
**=> The four sent traces are present**
4. Run the `json_counter` example
```
RUST_LOG=debug cargo run --example json_counter
```
**=> You must see TLS handshake debug logs**
> DEBUG [rustls::client::hs] No cached session for DnsName("test.mosquitto.org")  
> DEBUG …

rust: telemetry basic auth + MQTT trust store TLS

---

python/its-vehicle/its_vehicle/main.py

**Bug-fix:**
* Workaround authentication in its-vehicle
---
***How to test:*
1. Start an OpenTelemetry collector with Basic Auth.
2. Install its-vehicle
3. Enable telemetry in its-vehicle:
```cfg
[telemetry]
endpoint = http://your-otlp-collector:4318
username = USER
password = PASSWD
```
4. Look at the traces in your OTLP collector
---
The its-vehicle traces appear in the OTLP collector.

python/vehicle: hot-fix for OpenTelemetry authentication

---

python/iot3/src/iot3/core/mqtt.py
python/iot3/src/iot3/core/otel.py

**Features**;
* Extend OpenTelemetry attributes
* common, generic attribute `iot3.core.sdk_language`
* MQTT attributes `iot3.core.mqtt.payload_size` and `iot3.core.mqtt.topic`
---
1. Prepare an OpenTelemetry collector on localhost:
```
--rm \
-p 4318:4318 \
```
then open a browser on the Jaegger UI:
```
http://localhost:16686/
```
2. Start an MQTT client:
```
$ mosquitto_sub \
-h test.mosquitto.org -p 1883 \
-t 'test/+/iot3/#' \
-F '%j' \
| jq -C .
```
3. Test IoT3 Core SDK:
1. start an environment with python 3.11:
```sh
--rm \
-ti \
-e no_proxy \ …
```

python/iot3: extend OpenTelemetry attributes

---

python/its-interqueuemanager/its-iqm.cfg
python/its-interqueuemanager/its_iqm/iqm.py

**Bug fix:**
* closes #194
---
1. start two MQTT brokers; the socket is considered "local", and 1235 is considered the "neighbour"; start an MQTT client on the local broker:
```sh
$ cat >mosquitto.cfg <<_EOF_
per_listener_settings true
listener 0 /tmp/mqtt.sock
allow_anonymous true
_EOF_
$ mosquitto -c mosquitto.cfg
$ mosquitto -p 1234
$ mosquitto_sub --unix /tmp/mqtt.sock -t '#' -F '%U %t %p'
```
2. Install IoT3 Core SDK and its-iqm:
1. start a docker container with python 3.11 (if you already have python 3.11 or later on your machine, you don't need the container):
```sh
--rm \
-ti \
-e no_proxy \
--mount type=bind,source=/tmp/mqtt.sock,destination=/tmp/mqtt.sock \ …
```

python/iqm: fix subscribing to neighbours, take 2

---

java/iot3/mobility/src/main/java/com/orange/iot3mobility/IoT3Mobility.java

**Fixes**;
IoT3 Mobility SDK:
Fix topic root for CAM, DENM and CPM publication : it is now correctly set according to the "context" parameter.
---
3. Find the ```Iot3MobilityExample``` class in the ```examples``` module, and set appropriate values for the following fields:
```
private static final String EXAMPLE_CONTEXT = "context"; // this will be used as the topic root
// MQTT parameters
private static final String EXAMPLE_MQTT_HOST = "mqtt_host";
private static final int EXAMPLE_MQTT_PORT = 1883;
private static final String EXAMPLE_MQTT_USERNAME = "mqtt_username";
private …
```

java/iot3mobility: fix topic root for mobility messages publication

---

rust/examples/copycat.rs
rust/examples/json_counter.rs
rust/examples/telemetry.rs
rust/src/client/application/pipeline.rs
rust/src/transport/mqtt/mqtt_client.rs
rust/src/transport/mqtt/mqtt_router.rs
rust/src/transport/telemetry.rs

What's new
- Trace MQTT message reception
- Trace MQTT message publishing
- Set the W3C context as MQTTv5 user property in published message
- Extract W3C context from received message if any
Closes #124 
How to test
1. Start a Jaeger/OTLP collector image
```
docker run --rm --name jaeger \
-e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
-p 6831:6831/udp \
-p 6832:6832/udp \
-p 5778:5778 \
-p 4317:4317 \
-p 4318:4318 \
-p 14250:14250 \
-p 14268:14268 \
-p 14269:14269 \
-p 9411:9411 -d\
```
2. Create the test script
```
wget https://github.com/user-attachments/files/17507082/test_copycat.txt &&
mv test_copycat.txt /tmp/test_copycat.sh &&
chmod +x /tmp/test_copycat.sh
```
(or download it as txt …

Rust  MQTT telemetry

---

python/its-status/its_status/collector.cellular.py
python/its-vehicle/its_vehicle/client.py

**Changes:**
* Fixes: #198 
* Fixes: #203 
---
1. The fix for #198 is hard to validate, as the condition seldom occurs in practice...
2. Test the fix for #203: 
1. install _its-vehicle_ and its dependencies
2. configure _its-vehicle_ with both a remote and a local MQTT broker
3. run _its-vehicle_
4. observe the quadkeys in the topic of messages received by the remote broker
5. send a message to the remote broker, on a topic which quadkeys is _close_ to the messages above
---
1. _its-status_ does not crash anymore
2. the message sent in step _v._ is received on the local broker

python: fix issues 198 & 203

---

schema/dsrc_schema_1-0-0.json
schema/srem_schema_1-0-0.json
schema/ssem_schema_1-0-0.json

**What's new**;
JSON Schemas:
Added SREM and SSEM schemas, alongside a DSRC schema regrouping common definitions for both SREM and SSEM (to be completed for future needs).
closes #184 and closes #183 
---
**What to do**:
1. Read the new schemas and check them against [ETSI repository docs](https://forge.etsi.org/rep/ITS/asn1/is_ts103301/-/tree/release2/docs) for potential mistakes.
2. Evaluate and discuss the impact of the use of new DSRC "units" before merging.

Add SREM / SSEM and DSRC library JSON Schemas

---

rust/examples/telemetry.rs
rust/src/client/application.rs
rust/src/exchange/etsi/collective_perception_message.rs
rust/src/exchange/etsi/mobile_perceived_object.rs

New features
- rust: new `create_cam` function allowing to create a CooperativeAwarenessMessage from minimal information (fixes #131)
- rust: fix MobilePerceivedObject heading computation (fixes #98) 
How to test
1. Launch json_counter example
```
cargo run --example json_counter
```
**Example runs and yields about the number of JSON messages received among the total**
> Received 1000 messages including 997 as JSON  
> Received 2000 messages including 1997 as JSON  
> Received 3000 messages including 2997 as JSON  
> ...
2. Configure OTLP collector
Edit the `example/config.ini` file to set the OTLP collector endpoint config by filling the following section
```
[telemetry]
host="otlp.domain.ext"
port=4318
; Optionnal, defaults to "v1/traces" …
```

Rust client functions

---

rust/Cargo.toml
rust/examples/config.ini
rust/src/client.rs
rust/src/client/bootstrap.rs
rust/src/client/bootstrap/bootstrap_error.rs
rust/src/client/configuration.rs
rust/src/client/configuration/bootstrap_configuration.rs
rust/src/client/configuration/configuration_error.rs
rust/src/client/configuration/geo_configuration.rs
rust/src/client/configuration/mobility_configuration.rs
rust/src/client/configuration/node_configuration.rs
rust/src/client/configuration/telemetry_configuration.rs

What's new
New function to create a Configuration from bootstrap sequence  
The bootstrap sequence provide services' URL and credentials, any of these information already present in the configuration file
All the other fields that are unrelated to services connection are still read from the configuration file and set in the Configuration object
closes #185 
closes #161 
How to test
1. Edit `examples/config.ini` and 
1. Fill the `[bootstrap]` section with the proper endpoint and credentials
2. Remove the `[mqtt]` section
3. Remove the ``telemetry]` section
2. Apply the joined [patch][1] to make the `copycat` example using the bootstrap sequence
```
cd rust
wget https://github.com/user-attachments/files/17728759/copycat_bootstrap.txt
mv copycat_bootstrap.txt …
```

Rust authority bootstrap

---

python/iot3/pyproject.toml
python/iot3/src/iot3/mobility/__init__.py
python/iot3/src/iot3/mobility/cam.py
python/iot3/src/iot3/mobility/denm.py
python/iot3/src/iot3/mobility/etsi.py
python/iot3/src/iot3/mobility/gnss.py
python/iot3/tests/test-iot3-mobility
python/iot3/tests/test-iot3-mobility-gnss
python/iot3/tests/test-iot3-mobility-message

**Features:**
* Closes: #132
---
**Preparation:**
1. if you do not have a gpsd server listening on `localhost:2947`, spawn one (needs gpsd 3.24 or later):
* grab the [NMEA sample on Wikipedia](https://en.wikipedia.org/wiki/NMEA_0183#Sample_file) and save it in a file called `NMEA.log`
* start a gpsfake using that file to emulate a GNSS device:
```sh
TMPDIR=/tmp gpsfake -q -P 2947 -o=-G -u -n -c 0.1 NMEA.log
```
2. if you do not have python 3.11 or later, you can use the following to create a container to run all the tests:
* start a container with python 3.11:
```sh
--detach \
--name iot3 \
--rm \
-ti \
-e no_proxy \ …
```

python/iot3: implement mobility SDK

---

python/its-vehicle/its-vehicle.cfg
python/its-vehicle/its_vehicle/main.py

**Changes:**
* Bug fix: closes #192
---
Pre-requisites:
* a python 3.11 environment; if you do not have one already, use a container:
```sh
--detach \
--name iot3 \
--rm \
-ti \
-e no_proxy \
/bin/bash -il
$ docker container exec -u 0:0 iot3 apt install -y build-essential
$ docker container attach iot3
```
* a gpsd daemon listening on _localhost_ on port 2947; if you do not have one already (needs gpsd 3.24 or later; `NEMA.log` is a file containing NME sentences, like the sample on …

python/its-vehicle: make authentication configurable

---

schema/cpm/cpm_schema_1-2-2.json

**Features:**
* Fix CPM schema syntax
Closes: #216
Note: GitHub does not detect that the 1.2.2 schema is a copy of the 1.2.1 one with just a single line changed; the changes are best viewed locally with `git show -C98`.
---
1. Check the [workflow job for CPM schema 1.2.2](https://github.com/Orange-OpenSource/its-client/actions/runs/12084281003/job/33699141815?pr=233)
---
1. The job succeeds (no validation error occcurs[*])
[*] we know we have a problem with validation, in that validation issues are not all detected and reported, but at least the above is a minimal sanity check...

schema/cpm: fix syntax

---

java/iot3/mobility/src/main/java/com/orange/iot3mobility/its/HazardType.java

An internal easter-egg was forgotten by mistake and has now been removed from the code base.

java/iot3mobility: remove DENM easter-egg

---

python/its-interqueuemanager/its-iqm.cfg
python/its-interqueuemanager/its_iqm/iqm.py
python/its-interqueuemanager/its_iqm/main.py

**Changes:**
* Bug fix: closes #224
---
Pre-requisites:
* an MQTT broker listening on `localhost:1883`; if you do not have one, you can just run:
```sh
$ mosquitto
```
* an OpenTelemetry collector with authentication
* a python 3.11 environment; if you do not have one already, use a container:
```sh
--detach \
--name iot3 \
--rm \
-ti \
-e no_proxy \
/bin/bash -il
$ docker container exec -u 0:0 iot3 apt install -y build-essential git socat
$ docker container exec -d iot3 socat UNIX-LISTEN:/tmp/mqtt.socket,fork …
```

python/iqm: allow authentication for telemetry

---

java/iot3/mobility/src/main/java/com/orange/iot3mobility/IoT3Mobility.java

**What's new**
The IoT3Core instance powering IoT3Mobility is now exposed to the user.
---
3. Find the ```Iot3MobilityExample``` class in the ```examples``` module.
4. Check that you can call the getter `getIoT3Core()` from the `ioT3Mobility` object, and that you have access to its underlying methods (for instance, `mqttPublish()` and `mqttSubscribe()`).

java/iot3mobility: add IoT3Core getter to IoT3Mobility

---

schema/denm/denm_schema_2-1-0.json

What's new
----------------
All changes listed here below concern the DENM schema differences between 2.0.0 and 2.1.0 versions
1. Add references to the document used to write this schema Comment has been added to the TS (Technical specification) file reference to indicate that it is prefered to solve conflicts that may be present against the EN (European standard) one
2. Mutualized the following two object types in `$defs`
- information_quality
- delta_reference_position
3. `management_container`
1. Clarify reference_time vs. detection_time by adding comments (cf. gh#223)
2. Rename `relevance_distance` to `awareness_distance`
3. Removed `confidence` field Instead, `event_position` object now carries its confidence
4. `situation_container`
1. Added new optionnal field `event_zone`
2. Added …

schema: new version 2.1.0 for DENM

---

schema/cam/cam_schema_2-1-0.json

**Features:**
* Update CAM schema according to CAM ETSI TS 103 900 V2.1.1
Closes: #217
---
1. Check the [workflow job for CAM schema 2.1.0](https://github.com/Orange-OpenSource/its-client/actions/runs/12320560607)
2. Compare the 2.1.0 schema to the  CAM ETSI TS 103 900 V2.1.1 (https://forge.etsi.org/rep/ITS/asn1/cam_ts103900/-/tree/V2.1.1)
---
1. The job succeeds (no validation error occcurs)
2. The 2.1.0 CAM schema should correspond to the Technical Specification

schema/cam update schema according to CAM ETSI TS 103 900 V2.1.1

---

python/its-interqueuemanager/pyproject.toml
python/its-status/pyproject.toml
python/its-vehicle/pyproject.toml

**Changes:**
* Bug fix:
* Closes: #255
* Fix dependencies on IoT3 (due to unpublished packages)
---
Pre-requisites:
* a python 3.11 environment; if you do not have one already, use a container:
```sh
--detach \
--name iot3 \
--rm \
-ti \
-e no_proxy \
/bin/bash -il
$ docker container exec -u 0:0 iot3 apt install -y build-essential git
$ docker container attach iot3
```
Note: in the following the `$` prompt means running in a shell that has access to python3.11, while the `🐍 $` prompt means running in the activated _venv_.
1. …

python: fix installed scripts

---

python/iot3/src/iot3/core/__init__.py
python/iot3/src/iot3/mobility/__init__.py
python/iot3/tests/test-iot3-core-bootstrap
python/iot3/tests/test-iot3-mobility-bootstrap

**Features:**
* Closes: #186 
---
**Preparation:**
1. Start a bootstrap manager
* edit `python/iot3/tests/test-iot3-core-bootstrap` and `python/iot3/tests/test-iot3-mobility-bootstrap` with the details of your bootstrap manager, notably the host, port, endpoint, credentials...
2. if you do not have python 3.11 or later, you can use the following to create a container to run all the tests:
* start a container with python 3.11:
```sh
--detach \
--name iot3 \
--rm \
-ti \
-e no_proxy \
/bin/bash -il
```
* install the necessary packages:
```sh
$ …
```

python/iot3: add bootstrap

---

.github/workflows/swift.yml
CONTRIBUTORS.md
THIRD-PARTY.md
licenses/LICENSE-mqtt-nio (Apache 2.0).txt
swift/ITSClient/.swiftpm/xcode/xcshareddata/xcschemes/ITSClient.xcscheme
swift/ITSClient/Package.resolved
swift/ITSClient/Package.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTClient.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTClientConfiguration.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTClientError.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTMessage.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTNIOClient.swift
swift/ITSClient/Tests/ITSClient.xctestplan
swift/ITSClient/Tests/ITSCoreTests/MQTTNIOClientTests.swift

**What's new**
Add a implementation of a MQTT client with MQTT NIO
---
1. Clone the its-client project.
2. Run the MQTTNIOClientTests which use the MQTT client in different cases.
Closes #253

swift: add MQTT client

---

rust/src/transport/mqtt/mqtt_client.rs

What's new
- rust: remove unused lifetime declaration in MqttClient (fixes #260)
How to test
1. Check that all jobs in workflows succeeded

rust: remove unused lifetime declaration

---

CONTRIBUTORS.md
python/iot3/pyproject.toml
python/iot3/src/iot3/core/__init__.py
python/iot3/src/iot3/core/mqtt.py
python/iot3/tests/test-iot3-core

**Changes:**
* Feature: allow using the simple API without OTLP
Closes: #236 
---
0. Pre-requisites:
* an OpenTelemetry collector on localhost:
```sh
--rm \
-p 4318:4318 \
```
* a python 3.11 environment; if you do not have one already, use a container:
```sh
--detach \
--name iot3 \
--rm \
-ti \
-e no_proxy \
/bin/bash -il
$ docker container exec -u 0:0 iot3 apt install -y git
$ docker container attach iot3
```
Note: in the following tests, the `$` …

python/iot3: make OTLP optional in simple API

---

.github/workflows/swift.yml
README.md
THIRD-PARTY.md
licenses/LICENSE-opentelemetry-swift (Apache 2.0).txt
swift/ITSClient/Package.resolved
swift/ITSClient/Package.swift
swift/ITSClient/Sources/ITSCore/Telemetry/OpenTelemetryClient.swift
swift/ITSClient/Sources/ITSCore/Telemetry/TelemetryClient.swift
swift/ITSClient/Sources/ITSCore/Telemetry/TelemetryClientConfiguration.swift
swift/ITSClient/Tests/ITSCoreTests/OpenTelemetryClientTests.swift

**What's new**
Add a implementation of an OpenTelemetry client with open-telemetry-swift 
---
1. Clone the its-client project and check out the branch under review
2. Run a local OpenTelemetry collector with a http endpoint on port 4318:
```sh
--rm \
-p 4318:4318 \
```
3. Run the test OpenTelemetryClientTests.send_several_consumer_and_producer_spans:
```sh
swift test --filter OpenTelemetryClientTests.send_several_consumer_and_producer_spans   
```
Expected result:  Check on the Jaeger UI (on http://localhost:16686/) that 10 consumers and 10 producers spans have been created.
4. Run the test OpenTelemetryClientTests.send_producer_and_child_consumer_span:
```sh
swift test --filter …
```

swift: add telemetry client

---

java/iot3/mobility/src/main/java/com/orange/iot3mobility/managers/RoadHazardManager.java

**Fixes**
- Fixed the UUID of `RoadHazard` from the combination of the `DENM`'s `source_uuid` and `station_id`, to the correct combination of `originating_station_id` and `sequence_number`.
- Fixed handling of `DENM` termination to trigger the removal of the corresponding `RoadHazard` from the HashMap holding the active road hazards + notification to the callback.
Closes #280 
---
**To do**
Just review the code changes.

Java: fix road hazard handling

---

swift/ITSClient/Sources/ITSCore/Core.swift
swift/ITSClient/Sources/ITSCore/CoreConfiguration.swift
swift/ITSClient/Sources/ITSCore/CoreError.swift
swift/ITSClient/Sources/ITSCore/CoreMQTTMessage.swift
swift/ITSClient/Sources/ITSCore/EquatableError.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTClient.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTClientConfiguration.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTClientError.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTMessage.swift
swift/ITSClient/Sources/ITSCore/MQTT/MQTTNIOClient.swift
swift/ITSClient/Sources/ITSCore/Telemetry/TelemetryClientConfiguration.swift
swift/ITSClient/Tests/ITSCoreTests/CoreTests.swift
swift/ITSClient/Tests/ITSCoreTests/CoreUnitTests.swift
swift/ITSClient/Tests/ITSCoreTests/MQTTNIOClientTests.swift
swift/ITSClient/Tests/ITSCoreTests/MockMQTTClient.swift
swift/ITSClient/Tests/ITSCoreTests/MockTelemetryClient.swift

**What's new**
Add a implementation of the Core which uses a MQTTClient and a TelemetryClient to perform MQTT operations with traces.
---
1. Clone the its-client project and check out the branch under review
2. Run a local OpenTelemetry collector with a http endpoint on port 4318:
```sh
--rm \
-p 4318:4318 \
```
3. Run the test CoreTests.message_sent_to_subscribed_topic_should_be_received_and_create_linked_span:
```sh
swift test --filter CoreTests.message_sent_to_subscribed_topic_should_be_received_and_create_linked_span   
```
Expected result:  Check on the Jaeger UI (on http://localhost:16686/) that that 1 producer span and 1 consumer span which references the producer have been created.
4. Run the …

swift: add core

---

java/iot3/core/src/main/java/com/orange/iot3core/IoT3Core.java
java/iot3/core/src/main/java/com/orange/iot3core/bootstrap/BootstrapHelper.java
java/iot3/core/src/main/java/com/orange/iot3core/clients/MqttClient.java
java/iot3/core/src/main/java/com/orange/iot3core/clients/OpenTelemetryClient.java
java/iot3/examples/src/main/java/com/orange/Iot3CoreExample.java
java/iot3/examples/src/main/java/com/orange/Iot3MobilityBootstrapExample.java
java/iot3/examples/src/main/java/com/orange/Iot3MobilityExample.java
java/iot3/mobility/src/main/java/com/orange/iot3mobility/IoT3Mobility.java

**Features**;
Telemetry is now optional for the IoT3 Core and Mobility SDKs.
Closes #235 
---
```
private static final String BOOTSTRAP_ID = "bootstrap_id";
private static final String BOOTSTRAP_LOGIN = "boostrap_login";
private static final String BOOTSTRAP_PASSWORD = "bootstrap_password";
private static final BootstrapHelper.Role BOOTSTRAP_ROLE = …
```

java: make telemetry optional

---

java/iot3/core/build.gradle
java/iot3/core/src/main/java/com/orange/iot3core/bootstrap/BootstrapHelper.java

**Fix**
The `OkHttp` library is replacing the Android-incompatible `java.net.http` library (part of Java 11 and Android is based on Java 8).
Closes #288 
---
```
private static final String BOOTSTRAP_ID = "bootstrap_id";
private static final String BOOTSTRAP_LOGIN = "boostrap_login";
private static final String BOOTSTRAP_PASSWORD = "bootstrap_password";
private …
```

java/iot3core: fix bootstrap for Android compatibility

---

java/iot3/examples/src/main/java/com/orange/Iot3MobilityBootstrapExample.java
java/iot3/examples/src/main/java/com/orange/Iot3MobilityExample.java
java/iot3/mobility/src/main/java/com/orange/iot3mobility/IoT3Mobility.java
java/iot3/mobility/src/main/java/com/orange/iot3mobility/IoT3RawMessageCallback.java

**Feature**
A new "raw message callback" allows the host application to retrieve raw messages before they are being treated by the SDK.
Closes #312 
---
```
private static final String BOOTSTRAP_ID = "bootstrap_id";
private static final String BOOTSTRAP_LOGIN = "boostrap_login";
private static final String BOOTSTRAP_PASSWORD = "bootstrap_password";
private static …
```

java: add raw message callback

---

python/iot3/src/iot3/core/mqtt.py
python/its-interqueuemanager/its-iqm.cfg
python/its-interqueuemanager/src/its_iqm/filters.py
python/its-interqueuemanager/src/its_iqm/iqm.py
python/its-interqueuemanager/src/its_iqm/main.py

**Changes:**
* IoT3 SDK:
* handle retain
* handle Message Expiry Interval MQTT property
* InterQueueManager:
* implement filtering
* match topic on regex or prefix
* drop
* set retain and Message Expiry Interval
Closes #292
Closes #293
---
_**Note:** in the folowing: lines starting with `$` are to be executed on your machine, as a non-root user; lines starting with `(docker)$` are to be executed in the Docker container; lines starting with `(docker)🐍 $` are to be executed in the Docker container, in the python `venv`._
1. Prepare an environment
1. ensure a mosquitto broker is listening on `localhost:1883`, without any ACL; if not, start one (no need to be root):
```sh
$ mosquitto
```
then in another terminal, run an MQTT client that dumps mesages going through the broker: …

python: handle retain in IoT3 SDK, allow filtering in IQM

---

rust/src/exchange.rs

What's new
- Add `mobile_id` a `Exchange::PathElement` member
How to test
1. Check that no pipelines failed

rust: add mobile_id in Exchange::PathElement

---

java/iot3/core/src/main/java/com/orange/iot3core/IoT3Core.java
java/iot3/core/src/main/java/com/orange/iot3core/clients/MqttClient.java
java/iot3/mobility/src/main/java/com/orange/iot3mobility/IoT3Mobility.java

**Feature**
The IoT3 Core MQTT client now has an automatic reconnection policy: reconnection will automatically be tried 500 ms after a connection loss the retry delay will gradually increase up to every 5 seconds.
The IoT3 Core and Mobility also expose respectively an isMqttConnected() and isConnected() method.
Closes #323 
---
```
private static final String …
```

java: add MQTT auto reconnect to IoT3 Core

---

python/iot3/src/iot3/core/mqtt.py
python/iot3/tests/test-iot3-core
python/iot3/tests/test-iot3-core-all
python/iot3/tests/test-iot3-core-mqtt

**Changes:**
* Bugfix:
* fix MQTT subscriptions using the IoT3 Core SDK
Closes #317 
---
1. Prepare a test environment:
1. be sure to have unrestricted access to _test.mosquitto.org_ (IPv4 and IPv6)
2. prepare an OpenTelemetry collector on localhost:
```
--rm \
-p 4318:4318 \
```
then open a browser on the Jaegger UI:
```
http://localhost:16686/
```
3. in another terminal, start a container with python 3.11 and the necessary packages:
```sh
--detach \
--name iot3 \
--rm \
-ti \
-e no_proxy \ …
```

python/iot3: fix MQTT subscriptions

---

java/iot3/mobility/src/main/java/com/orange/iot3mobility/IoT3Mobility.java
java/iot3/mobility/src/main/java/com/orange/iot3mobility/managers/RoadHazardManager.java
java/iot3/mobility/src/main/java/com/orange/iot3mobility/managers/RoadSensorManager.java
java/iot3/mobility/src/main/java/com/orange/iot3mobility/managers/RoadUserManager.java

**Feature**
The IoT3 Mobility SDK is now exposing its lists of `RoadUser`, `RoadHazard` and `RoadSensor` objects.
The lists are read-only to avoid modification by the host app.
Closes #332  
---
```
private static final String BOOTSTRAP_ID = "bootstrap_id";
private static final String BOOTSTRAP_LOGIN = "boostrap_login";
private static final String …
```

Java/iot3mobility: expose ITS objects lists

---

swift/ITSClient/Package.swift
swift/ITSClient/Sources/ITSMobility/Models/CAM/BasicContainer.swift
swift/ITSClient/Sources/ITSMobility/Models/CAM/CAM.swift
swift/ITSClient/Sources/ITSMobility/Models/CAM/CAMMessage.swift
swift/ITSClient/Sources/ITSMobility/Models/CAM/HighFrequencyContainer.swift
swift/ITSClient/Sources/ITSMobility/Models/CAM/LowFrequencyContainer.swift
swift/ITSClient/Sources/ITSMobility/Models/Confidence.swift
swift/ITSClient/Sources/ITSMobility/Models/DENM/AlacarteContainer.swift
swift/ITSClient/Sources/ITSMobility/Models/DENM/DENM.swift
swift/ITSClient/Sources/ITSMobility/Models/DENM/DENMMessage.swift
swift/ITSClient/Sources/ITSMobility/Models/DENM/LocationContainer.swift
swift/ITSClient/Sources/ITSMobility/Models/DENM/ManagementContainer.swift
swift/ITSClient/Sources/ITSMobility/Models/DENM/Position.swift
swift/ITSClient/Sources/ITSMobility/Models/DENM/SituationContainer.swift
swift/ITSClient/Sources/ITSMobility/Models/ETSI.swift
swift/ITSClient/Sources/ITSMobility/Models/MessageType.swift
swift/ITSClient/Sources/ITSMobility/Models/Origin.swift
swift/ITSClient/Sources/ITSMobility/Models/PathHistory.swift
swift/ITSClient/Sources/ITSMobility/Models/SequenceNumberGenerator.swift
swift/ITSClient/Sources/ITSMobility/Models/StationType.swift
swift/ITSClient/Tests/ITSClient-UnitTests.xctestplan
swift/ITSClient/Tests/ITSMobilityTests/CAMTests.swift
swift/ITSClient/Tests/ITSMobilityTests/DENMTests.swift
swift/ITSClient/Tests/ITSMobilityTests/Data/Cam.json
swift/ITSClient/Tests/ITSMobilityTests/Data/Denm.json
swift/ITSClient/Tests/ITSMobilityTests/FileLoader.swift

**What's new**
Add the CAM and DENM objects. Allow to encode or decode the objects in JSON.
---
Just check the code and the unit tests to be sure that the schemas are respected.
Closes #341

swift: add ETSI entities

---

.github/PULL_REQUEST_TEMPLATE/README
.github/pull_request_template.md

**Changes:**
* github: add a generic PR template
* Closes: #345 
Note: it is not possible to test this until it has landed in the master branch, as GitHub only takes templates from there.

github: make PR templates somewhat usable

---

swift/ITSClient/Sources/ITSMobility/Mobility.swift
swift/ITSClient/Sources/ITSMobility/RegionOfInterest/RegionOfInterest.swift
swift/ITSClient/Sources/ITSMobility/RegionOfInterest/RegionOfInterestCoordinator.swift
swift/ITSClient/Tests/ITSClient-IntegrationTests.xctestplan
swift/ITSClient/Tests/ITSMobilityTests/RegionOfInterestCoordinatorTests.swift

**What's new**
Add the region of interest which allows to manage MQTT subscriptions depending the coordinates and the zoom level.
Add a method to update the road alarm region of interest
Add a method to update the road position region of interest
---
Just check the code and the unit tests.
Closes #363

swift: region of interest

---

rust/src/client/application/pipeline.rs

What's new
* rust: fixed channel sender disconnection handling
* rust: restored loop in pipeline to recover from MQTT disconnection (closes #328)
How to test
1. Edit `example/config.ini` to set the `mqtt.port` to 58886 (or any non valid port from test.mosquitto.org)
2. Start the copycat example
```
cargo run --example copycat -- --features geo_routing
```
**=> The pipeline starts, fails to connect to the MQTT broker and threads end**  
> [2025-04-25 10:46:12.496108 +02:00] T[tokio-runtime-worker] ERROR [src/transport/mqtt/mqtt_client.rs:124] Stopped to receive event: Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })  
> [2025-04-25 10:46:12.496536 +02:00] T[tokio-runtime-worker] WARN [src/transport/mqtt/mqtt_client.rs:129] …

rust: fix MQTT disconnection handling

---

swift/ITSClient/Sources/ITSCore/MQTT/MQTTNIOClient.swift

**What's new**
Remove the deprecated property when initializing the MQTTNIO MQTTClient.
---
Run the MQTTNIOClientTests tests.
Closes #371

swift: replace the MQTTNIO deprecated property

---

swift/ITSClient/Sources/ITSCore/Core.swift
swift/ITSClient/Sources/ITSMobility/Mobility.swift
swift/ITSClient/Sources/ITSMobility/MobilityError.swift
swift/ITSClient/Tests/ITSCoreTests/CoreTests.swift
swift/ITSClient/Tests/ITSCoreTests/CoreUnitTests.swift
swift/ITSClient/Tests/ITSMobilityTests/MobilityTests.swift
swift/SampleApp/SampleApp/Mobility/Data/ITSMobilityService.swift
swift/SampleApp/SampleApp/Mobility/Domain/MobilityError.swift
swift/SampleApp/SampleApp/Mobility/Domain/MobilityService.swift
swift/SampleApp/SampleApp/Mobility/UI/MobilityView.swift
swift/SampleApp/SampleApp/Mobility/UI/MobilityViewModel.swift

**What's new**
The stop action never fails. The MQTT instance is destroyed even if a MQTT disconnect error occurs.
Closes #385

swift: stop Core properly when an error occurs

---

swift/ITSClient/Sources/ITSCore/Core.swift
swift/ITSClient/Tests/ITSCoreTests/CoreTests.swift

**What's new**
Calling several times the Core start method when the broker or the connection is down will throw a connection failed error each time.
---
Run the test called `start_core_twice_should_throw_an_error_each_time`
Closes #387

swift: start Core should throw an error each time when the connection fails

---

swift/ITSClient/Sources/ITSMobility/Mobility.swift
swift/ITSClient/Sources/ITSMobility/Observers/Cache.swift
swift/ITSClient/Sources/ITSMobility/Observers/RoadAlarm/RoadAlarmCoordinator.swift
swift/ITSClient/Sources/ITSMobility/Observers/RoadUser/RoadUserCoordinator.swift
swift/ITSClient/Sources/ITSMobility/RegionOfInterest/RegionOfInterestCoordinator.swift

**What's new**
When the mobility stack is stopped, the subscriptions are reset. The road object caches are also reset and the client will be notified with delete events to clean the objects on its side.
Closes #422

swift: fix mobility stop

---

java/iot3/core/build.gradle
java/iot3/core/src/main/java/com/orange/iot3core/clients/lwm2m/Lwm2mClient.java
java/iot3/core/src/main/java/com/orange/iot3core/clients/lwm2m/model/Lwm2mConfig.java
java/iot3/core/src/main/java/com/orange/iot3core/clients/lwm2m/model/Lwm2mConnectivityStatistics.java
java/iot3/core/src/main/java/com/orange/iot3core/clients/lwm2m/model/Lwm2mDevice.java
java/iot3/core/src/main/java/com/orange/iot3core/clients/lwm2m/model/Lwm2mInstance.java
java/iot3/core/src/main/java/com/orange/iot3core/clients/lwm2m/model/Lwm2mServer.java
java/iot3/examples/src/main/java/com/orange/Iot3CoreExample.java
java/iot3/examples/src/main/java/com/orange/Iot3MobilityExample.java

**Summary**
This PR upgrades the LwM2M client component to Eclipse Leshan 2.0.0-M15 and implements Queue Mode functionality for LwM2M v1.1 clients. The changes include necessary code adjustments to maintain compatibility with the new Leshan version and extend the configuration to support Queue Mode operation.
**Changes**
- Upgraded Eclipse Leshan dependencies from 1.5.0 to 2.0.0-M15
- Implemented Queue Mode functionality for LwM2M v1.1 clients
- Updated method signatures and client initialization to match Leshan 2.0.0 API
- Modified binding mode handling to use BindingMode instead of String
- Added configuration options for Queue Mode in Lwm2mConfig classes
- Fixed resource change notification mechanism
- Updated examples to demonstrate the new configuration options
**Issues Closed** …

LwM2M Client: Upgrade to Leshan 2.0.0-M15 (with queue Mode)
