.github/workflows/crates.yml, rust/its-client/Cargo.toml, rust/its-client/README.md, rust/libits-client/Cargo.toml, rust/libits-client/README.md, rust/libits-copycat/Cargo.toml, rust/libits-copycat/README.md
Fix the parallel publishing of the 3 Rust libraries.
Add badges on crates.io.
=> Fix crates workflows on same version than previously

.github/workflows/docker.yml
Simplify Github workflow defintion.
Fixes #6
=> gh-workflow/docker: drop superfluous fields

python/its_client/mqtt/mqtt_worker.py, python/its_client/position/static.py
Fix GPS time position management in python client
=> Fix python static position

python/its_client/configuration.py, python/its_client/logger/logger.py, python/its_client/main.py, python/its_client/mqtt/mqtt_client.py
A) Local test:
1- Start the Python its client on a local mosquitto broker:
```
/home/kvmk8371/workspace/its-client/python/venv/bin/python /home/kvmk8371/workspace/its-client/python/its_client/main.py --mqtt-client-id ora_car_testoverwrite
2022-04-05 16:36:06,610 INFO: config loaded from /home/kvmk8371/workspace/its-client/python/its_client/its_client.cfg
2022-04-05 16:36:06,610 INFO: argument configuration:
2022-04-05 16:36:06,610 INFO: mqtt_hostname: None
2022-04-05 16:36:06,610 INFO: mqtt_port: None
2022-04-05 16:36:06,610 INFO: mqtt_tls_port: None
2022-04-05 16:36:06,610 INFO: mqtt_username: None
2022-04-05 16:36:06,610 INFO: mqtt_password: ****
2022-04-05 16:36:06,610 INFO: mqtt_client_id: ora_car_testoverwrite
2022-04-05 16:36:06,610 INFO: static: None
2022-04-05 …
```
=> Stop on disconnect

.github/workflows/schema.yml, schema/ls, schema/status_schema_0-0-0.json, schema/status_schema_1-0-0.json
Kickstart the schema for status messages.
=> schema/status: prelimiminary schema for status messages

python/its-status/its_status/collector.cellular.py
**Bug fix:**
* #49: python/its-status: traceback in cellular KPIs retrieval
---
Proper testing would require being able to force various access technologies
(umts, gsm...), so requires quite a bit of involvement...
---
Fixes: #49
=> python/its-status: robustness (#49)

python/its-status/its-status.cfg, python/its-status/its_status/__init__.py, python/its-status/its_status/collector.cellular.py, python/its-status/its_status/collector.gnss.py, python/its-status/its_status/collector.static.py, python/its-status/its_status/collector.system.py, python/its-status/its_status/collector.time_sources.py, python/its-status/its_status/emitter.mqtt.py, python/its-status/its_status/emitter.stdout.py, python/its-status/its_status/main.py, python/its-status/setup.py
**Features:**
* switch from a [signal(7)](https://linux.die.net/man/7/signal) to a [timerfd(2)](https://linux.die.net/man/2/timerfd_create) to drive the main loop
* run plugins in their own individual threads
---
See #43 
---
See #43
=> python/its-status: re-architect main loop and data capturing

schema/neighbourhood_schema_1-0-0.json, schema/region_schema_1-0-0.json
=> Schema: introduce new schemas for region and neighborhood

.github/workflows/python_its-client.yml, .github/workflows/python_its-info.yml, .github/workflows/python_its-iqm.yml, .github/workflows/python_its-quadkeys.yml, .github/workflows/python_its-status.yml, .github/workflows/python_its-vehicle.yml
**Bug fix**
* Fixes: #152
---
1. Check status for all python workflows
---
1. All python workflows succeed
=> github/workflows: don't upload python artefacts

.github/workflows/java_iot3-core.yml, .github/workflows/java_iot3-examples.yml, .github/workflows/java_iot3-mobility.yml
**Features**;
GitHub Workflows:
Java workflows have been added for IoT3 Core, Mobility and Examples modules.
---
1. Clone the `mathieu1fb/its-client` fork.
2. Checkout to the `feature/workflow` branch.
2. Change something harmless and push it to GitHub.
3. Check that the 3 java workflows are being triggered in the GitHub `Actions` tab.
---
The 3 workflows should pass successfully and you should get a `BUILD SUCCESSFUL` in the 5th step of each build (gradle build).
=> github/workflows: add java workflows

CONTRIBUTORS.md, README.md, java/iot3/README.md
**What's changed**;
- updated main `README` with quick description of the Java libs
- updated `CONTRIBUTORS` file
- added new `README` in the java/iot3 package, describing the Java Iot3 Core and Mobility libs
=> documentation: update general readme and contributors files, add readme to the java/iot3 package

schema/README.md
Added a readme to the `schema` section explaining:
- the purpose of the described messages,
- their versioning rules
Please give suggestions to improve it before merging.
=> schema: add readme

schema/srem/srem_schema_2-0-1.json, schema/ssem/ssem_schema_2-0-1.json
Created a version 2.0.1 of the SREM and SSEM JSON schemas that include references.
Closes #220 
Please check that the added references are fine.
=> schema: SREM and SSEM version 2.0.1

.github/workflows/python_iot3.yml, .github/workflows/python_its-client.yml, .github/workflows/python_its-info.yml, .github/workflows/python_its-iqm.yml, .github/workflows/python_its-quadkeys.yml, .github/workflows/python_its-status.yml, .github/workflows/python_its-vehicle.yml, python/iot3/src/iot3/mobility/__init__.py, python/iot3/src/iot3/mobility/cpm.py, python/iot3/src/iot3/mobility/denm.py, python/iot3/src/iot3/mobility/etsi.py, python/iot3/tests/test-iot3-mobility-message
**Features:**
* Closes: #158
---
**Preparation:**
1. if you do not have python 3.11 or later, you can use the following to create a container to run all the tests:
* start a container with python 3.11:
```sh
--detach \
--name iot3 \
--rm \
-ti \
-e no_proxy \
/bin/bash -il
```
* install the necessary packages:
```sh
$ docker container exec -u 0:0 iot3 apt install -y git build-essential
```
* attach to the container:
```sh
$ docker container attach iot3
```
---
1. Create and activate a virtual-env to run the tests:
``` …
```
=> python/iot3/mobility: implement sensor message (CPM)

.github/workflows/swift.yml, .gitignore, swift/ITSClient/.gitignore, swift/ITSClient/Package.swift, swift/ITSClient/Sources/ITSClient/ITSClient.swift, swift/ITSClient/Tests/ITSClientTests/ITSClientTests.swift
**What's new**
Creation of the Swift Package ITSClient with Github workflow
---
1. Clone the its-client project.
2. Open the Package.swift in swift/ITSClient
3. Ensure that build & test are ok
4. Check the Github workflow
Closes #251
=> swift: Bootstrap library

THIRD-PARTY.md, licenses/LICENSE-opentelemetry-java (Apache 2.0).txt, licenses/LICENSE-square-okhttp (Apache 2.0).txt
**What's changed:**
Added Java OpenTelemetry and OkHttp to `THIRD-PARTY.md` plus their respective licenses.
---
**To-do:**
Check the new additions.
=> add missing Java licenses

swift/ITSClient/Sources/ITSCore/Core.swift, swift/ITSClient/Tests/ITSCoreTests/CoreTests.swift, swift/ITSClient/Tests/ITSCoreTests/CoreUnitTests.swift
**What's new**
Replace AsyncStream by a closure to measure the time passed in the closure (client code).
---
1. Clone the its-client project and check out the branch under review
2. Run a local OpenTelemetry collector with a http endpoint on port 4318:
```sh
--rm \
-p 4318:4318 \
```
3. Run the test CoreTests.message_sent_to_subscribed_topic_should_be_received_and_create_linked_span:
```sh
swift test --filter CoreTests.message_sent_to_subscribed_topic_should_be_received_and_create_linked_span   
```
Expected result:  Check on the Jaeger UI (on http://localhost:16686/) that that the consumer span last about 250 ms.
Closes #300
=> swift: measure the time in the client code when a message is received

swift/ITSClient/Package.swift, swift/ITSClient/Sources/ITSMobility/Mobility.swift
**What's new**
Add the mobility library to bootstrap the mobility client
Closes #302
=> swift: add mobility library

python/iot3/pyproject.toml, python/iot3/src/iot3/mobility/__init__.py, python/iot3/src/iot3/mobility/cpm.py, python/iot3/src/iot3/mobility/denm.py, python/iot3/src/iot3/mobility/etsi.py, python/iot3/tests/test-iot3-mobility, python/iot3/tests/test-iot3-mobility-message, python/its-info/pyproject.toml, python/its-interqueuemanager/pyproject.toml, python/its-status/pyproject.toml, python/its-vehicle/pyproject.toml
**Changes:**
* IoT3 SDK:
* mobility: add DENM subcause
* applications:
* all: update the iot3 dependency
* Closes: #262
---
_**Note:** in the following, lines starting with `$` are to be executed on your machine, as a non-root user; lines starting with `(docker)$` are to be executed in the Docker container; lines starting with `(docker)🐍 $` are to be executed in the Docker container, in the python venv._
1. Prepare a test environment:
1. be sure to have unrestricted access to _test.mosquitto.org_ (IPv4 and IPv6)
2. be sure to have an MQTT broker that listens locally on port 1883, with no credentials and no ACL; if not, run your own:
```sh
$ mosquitto
```
3. in another terminal, prepare a collector implementing the OpenTelemetry API, on localhost. If you don;t have one, …
=> python: add DENM subcause

.github/PULL_REQUEST_TEMPLATE/python.md, .github/PULL_REQUEST_TEMPLATE/rust.md, .github/pull_request_template.md, .github/workflows/codeql-analysis.yml, .github/workflows/rust-crates.yml, .github/workflows/rust-doc.yml, .github/workflows/rust.yml, rust/Cargo.toml, rust/README.md, rust/examples/collector.rs, rust/examples/config.ini, rust/examples/copycat.rs, rust/examples/json_counter.rs, rust/examples/telemetry.rs, rust/src/client.rs, rust/src/client/configuration.rs, rust/src/client/logger.rs
Execute the "Collector" example commands from the README.md file.
Check the first template.
Fix #319
Fix #330
Fix #352
=> Add file exporter collector

swift/ITSClient/Sources/ITSCore/Core.swift, swift/ITSClient/Sources/ITSCore/MQTT/MQTTNIOClient.swift, swift/ITSClient/Tests/ITSCoreTests/MQTTNIOClientTests.swift
**What's new**
Fix memory leaks in nested closure and add a test to verify memory leaks in MQTTNIOClient.
---
Just run the new test mqttnioclient_should_not_have_memory_leaks
Closes #372
=> swift: fix memory leaks in nested closures

rust/Cargo.toml, rust/README.md, rust/examples/config.ini, rust/examples/telemetry.rs, rust/src/client/bootstrap.rs, rust/src/client/configuration.rs, rust/src/client/configuration/bootstrap_configuration.rs, rust/src/client/configuration/telemetry_configuration.rs, rust/src/transport/telemetry.rs
Execute the "Telemetry" example commands from the README.md file.
Check the first template.
Fix #337
=> Add telemetry tls

.github/workflows/swift.yml, swift/SampleApp/SampleApp.xcodeproj/project.pbxproj, swift/SampleApp/SampleApp/Mobility/Data/ITSMobilityRoadAlarmChangeObserver.swift, swift/SampleApp/SampleApp/Mobility/Data/ITSMobilityService.swift, swift/SampleApp/SampleApp/Mobility/Domain/MobilityError.swift, swift/SampleApp/SampleApp/Mobility/Domain/MobilityService.swift, swift/SampleApp/SampleApp/Mobility/UI/MobilityView.swift, swift/SampleApp/SampleApp/Mobility/UI/MobilityViewModel.swift
**What's new**
Use the mobility SDK to send positions and receive alarms.
Closes #383
=> swift: use the mobility SDK to demonstrate it

swift/ITSClient/Sources/ITSCore/Bootstrap/Data/ITSBootstrapRequestDTO.swift, swift/ITSClient/Sources/ITSCore/Core.swift, swift/ITSClient/Sources/ITSCore/MQTT/MQTTClient.swift, swift/ITSClient/Sources/ITSCore/MQTT/MQTTNIOClient.swift, swift/ITSClient/Sources/ITSCore/Telemetry/OpenTelemetryClient.swift, swift/ITSClient/Sources/ITSCore/Telemetry/TelemetryClient.swift, swift/ITSClient/Tests/ITSCoreTests/CoreUnitTests.swift, swift/ITSClient/Tests/ITSCoreTests/MQTTNIOClientTests.swift, swift/ITSClient/Tests/ITSCoreTests/MockMQTTClient.swift, swift/ITSClient/Tests/ITSCoreTests/MockTelemetryClient.swift, swift/ITSClient/Tests/ITSCoreTests/OpenTelemetryClientTests.swift
**What's new**
Fix Swift 6 build errors in release.
Closes #397
=> swift: fix Swift concurrency

java/iot3/core/build.gradle, java/iot3/mobility/build.gradle
Changes
=======
IoT3 SDK:
* core: version set to 0.1.0 in the `build.gradle`
* mobility: version set to 0.1.0 in the `build.gradle`
Close #405 
Test
====
N/A
=> Version update

swift/ITSClient/Sources/ITSCore/MQTT/MQTTNIOClient.swift
**What's new**
The topic subscriptions are updated even if an MQTT error occurs on subscription or unsubscription (probably due to a broker or a network issue. These subscriptions will be resume after reconnecting.
Closes #366
=> swift: update subscriptions when an error occurs

swift/ITSClient/Sources/ITSMobility/Mobility.swift, swift/ITSClient/Sources/ITSMobility/RegionOfInterest/RegionOfInterestCoordinator.swift, swift/ITSClient/Tests/ITSMobilityTests/MobilityTests.swift, swift/ITSClient/Tests/ITSMobilityTests/RegionOfInterestCoordinatorTests.swift, swift/README.md, swift/SampleApp/SampleApp/Mobility/Data/ITSMobilityService.swift
**What's new**
A swift README has been added. Some public methods have been renamed to be consistent.
Closes #338
=> swift: add README
